spring:
  application:
    name: synonyms-register
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ree_dzenan
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/synonyms?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  #remove after enabling flyway
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    baseline-on-migrate: true

jwt:
  auth:
    converter:
      resource-id: synonyms-register-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8081'
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
